Disable submit button during form submit
wikimedia/wikimedia-ocr pull request #79
Opened 2023-04-30 23:22 UTC by PeterWarrington

A proposed fix for [Phabricator bug T334161 (Disable "Transcribe Full Page" button during transcription)](https://phabricator.wikimedia.org/T334161) which disables the button when the `onsubmit` event is fired. See the bug report itself for more info.

2023-05-01 21:38 UTC, kolakachi reviewed
We also have an input type of submit for the button Transcribe area. Can you disable it too on submit?

2023-05-02 01:25 UTC, PeterWarrington commented
> We also have an input type of submit for the button Transcribe area. Can you disable it too on submit?

Done - also made buttons re-enable on `pagehide` so that the buttons are re-enabled if the page is returned to via back button, etc.

2023-05-02 04:10 UTC, Parthiv-M requested changes
A couple of things I encountered:
- After I click on the _Transcribe whole page_ button and a response is returned, the _Transcribe whole page_ button is re-enabled, but the _Transcribe area_ button still stays disabled. Is that intended behaviour?
- Once I select an area using the crop tool and click on _Transcribe area_ button, the _Transcribe whole page_ button gets disabled on submit but the _Transcribe area_ button remains enabled throughout.

2023-05-02 20:10 UTC, PeterWarrington commented
@Parthiv-M 
The transcribe area button is intended to be disabled until a crop area is selected. 
I cannot replicate the other behaviour you describe locally in both Chrome and Firefox - both buttons disable themselves on submit for me. Can you let me know what browser environment you are testing in and verify that you are using the latest commits in this pull request?

2023-05-03 13:04 UTC, Parthiv-M commented
I tested with Firefox and have the latest commits from this PR. It does not seem to disable both the buttons when I click on _Transcribe area_.

2023-05-08 13:40 UTC, Parthiv-M commented
Hi @PeterWarrington, have you been able to resolve the issue?

2023-05-31 05:10 UTC, Parthiv-M commented
Hello @PeterWarrington , will you be making a patch soon for the above mentioned changes, or can we take over and complete the patch if you are caught up with something else?

2024-01-04 19:05 UTC, closed without merging