Add OCR models Fraktur and Latin for Tesseract
wikimedia/wikimedia-ocr pull request #85
Opened 2023-08-15 15:51 UTC by stweil

Both are not language specific, but support historic and current scripts used by many European languages.

2023-08-15 16:23 UTC, stweil commented
The installation provides some more Tesseract OCR models for scripts which could be added, too:

```
The following languages are installed but not supported:
Arabic
Armenian
Bengali
Canadian_Aboriginal
Cherokee
chi_sim_vert
chi_tra_vert
Cyrillic
Devanagari
div
Ethiopic
Georgian
Greek
Gujarati
Gurmukhi
Hangul
Hangul_vert
HanS
HanS_vert
HanT
HanT_vert
Hebrew
Japanese
Japanese_vert
jpn_vert
Kannada
Khmer
Lao
Malayalam
Myanmar
Oriya
Sinhala
Syriac
Tamil
Telugu
Thaana
Thai
Tibetan
Vietnamese
```

2023-08-15 16:27 UTC, stweil commented
Models for Akkadian and Khmer are available from [tessdata_contrib](https://github.com/tesseract-ocr/tessdata_contrib). Are those models interesting for Wikimedia, too?

2023-08-17 05:44 UTC, Parthiv-M commented
Hello, thanks for the PR! 

I believe the format in which you have added new models to `langs.json` is faulty. In general, every entry in `langs.json` is of the format

```bash
<wikisource-code>: {
       <engine-name>: <lang-or-model-code-according-to-engine>
}
```

You can find the list of language codes available on Tesseract on [this page](https://tesseract-ocr.github.io/tessdoc/Data-Files.html#data-files-for-version-400-november-29-2016). 

Also, [Latin](https://github.com/wikimedia/wikimedia-ocr/blob/5379cd194c1621929495492d021d7beaca79f434/public/langs.json#L335) (language code `lat`) and [German Fraktur](https://github.com/wikimedia/wikimedia-ocr/blob/5379cd194c1621929495492d021d7beaca79f434/public/langs.json#L107) (language code `frk`) are already present in `langs.json`. So, it does not make sense to add them again.

2023-08-17 07:04 UTC, stweil commented
lat and Latin are not the same models, but different ones, and so are frk and Fraktur. Both were trained by Ray Smith after 4.0.0 (which is covered by the documention in your link).

Latin and Fraktur are "script models", not "language models", so they cover all Western European languages with their supported characters and their dictionary (contrary to deu or frk which only covers German characters and a German dictionary).

2023-08-17 07:08 UTC, stweil commented
@Parthiv-M, you can try both new models (and the additional OCR engine kraken) [here](https://ocr.1.ladenburg.world/).

2023-08-17 07:11 UTC, stweil commented
The advantage of script models is that they work with text which contains several languages, for example German text with English or French names or a mix of German and Latin which is very common in historic texts. Here is a list of all available script models: https://github.com/tesseract-ocr/tessdata_fast/tree/main/script.

2023-08-17 07:36 UTC, Parthiv-M commented
Thanks for the clarification @stweil. The Latin and Fraktur models seem to work alright on the URL you provided, I'm just unsure about the naming convention to be followed while adding them to `langs.json`, since they are not the usual Tesseract models.

The Kraken OCR engine, on the other hand, would need a separate PR altogether, if it does get integrated.

@samwilson should be able to provide better insights on how to go about both of these.

2023-08-17 08:06 UTC, stweil commented
My implementation for the kraken OCR engine is [here](https://github.com/stweil/wikimedia-ocr/tree/kraken), but still incomplete: cropping and model selection are currently missing.

Kraken OCR is interesting because it will allow OCR on handwritten texts, too, so it is a free alternative to Transkribus OCR. UB Mannheim has some general [kraken models for printed and handwritten texts](https://ub-backup.bib.uni-mannheim.de/~stweil/tesstrain/kraken/), and even [more models](https://zenodo.org/communities/ocr_models/) are available.

2023-08-28 07:31 UTC, stweil commented
Ping @samwilson. Please merge.

2023-08-28 07:52 UTC, samwilson commented
Sorry for not looking at this earlier!

These extra models aren't yet installed on the production server (it's only got https://github.com/tesseract-ocr/tessdata_fast ). Can you provide details of how to install them? This might be the appropriate task for this work: https://phabricator.wikimedia.org/T284835

```
$ tesseract --list-langs
List of available languages (125):
afr
amh
ara
asm
aze
aze_cyrl
bel
ben
bod
bos
bre
bul
cat
ceb
ces
chi_sim
chi_sim_vert
chi_tra
chi_tra_vert
chr
cos
cym
dan
deu
div
dzo
ell
eng
enm
epo
equ
est
eus
fao
fas
fil
fin
fra
frk
frm
fry
gla
gle
glg
grc
guj
hat
heb
hin
hrv
hun
hye
iku
ind
isl
ita
ita_old
jav
jpn
jpn_vert
kan
kat
kat_old
kaz
khm
kir
kmr
kor
kor_vert
lao
lat
lav
lit
ltz
mal
mar
mkd
mlt
mon
mri
msa
mya
nep
nld
nor
oci
ori
osd
pan
pol
por
pus
que
ron
rus
san
sin
slk
slv
snd
spa
spa_old
sqi
srp
srp_latn
sun
swa
swe
syr
tam
tat
tel
tgk
tha
tir
ton
tur
uig
ukr
urd
uzb
uzb_cyrl
vie
yid
yor
```

2023-08-28 08:03 UTC, stweil commented
The easiest way to install all "fast" models is using the related Debian package (see [documentation](https://wikitech.wikimedia.org/wiki/Nova_Resource:Wikisource/Wikimedia_OCR)) which also includes Fraktur and Latin. But you can also get it from https://github.com/tesseract-ocr/tessdata_fast/tree/main/script.

2023-08-28 08:07 UTC, samwilson commented
Cool, thanks. I'll install it (although probably not this evening now…).

Actually, I think we're still running a compiled version but can now switch back to the distro one.

https://wikitech.wikimedia.org/wiki/Nova_Resource:Wikisource/Wikimedia_OCR#Latest_Tesseract

2024-06-16 15:50 UTC, stweil commented
@samwilson, is it possible now to merge my pull request?

2024-06-25 16:02 UTC, kolakachi requested changes
We already have latin added to the langs.json. There is a format for adding languages f.e.
```"la": { "tesseract":"latn"}```

2024-06-25 18:21 UTC, stweil commented
That's not the same. _la.traineddata_ is a recognition model for Latin language text with a Latin dictionary. _Latin.traineddata_ is a recognition model for Latin script which is used by most Western European countries. It includes a dictionary with words from all those countries (English, Spanish, German, French, Italian, ...). As many typical texts include a mixture of words from different languages, having a model which covers them all is very useful.

_Fraktur.traineddata_ is similar, a recognition model not only for Fraktur (used in Germany, Denmark), but also for historic characters like ligatures and ſ which were used in many Western countries. So historic English or French prints will need it, too.

2024-06-25 18:31 UTC, stweil commented
> "la": { "tesseract":"latn"}

I don't see a "latn" in the current code. There is only a "sr-latn".

2024-06-27 11:15 UTC, samwilson commented
Now we've upgraded the server, with the latest Tesseract, we have lots of new models:

```
rabic
Armenian
Bengali
Canadian_Aboriginal
Cherokee
Cyrillic
Devanagari
Ethiopic
Fraktur
Georgian
Greek
Gujarati
Gurmukhi
HanS
HanS_vert
HanT
HanT_vert
Hangul
Hangul_vert
Hebrew
Japanese
Japanese_vert
Kannada
Khmer
Lao
Latin
Malayalam
Myanmar
Oriya
Sinhala
Syriac
Tamil
Telugu
Thaana
Thai
Tibetan
Vietnamese
```

2024-06-27 11:16 UTC, merged