Add kraken OCR engine
wikimedia/wikimedia-ocr pull request #89
Opened 2023-08-19 11:13 UTC by stweil

2023-08-19 11:17 UTC, stweil commented
This is a first implementation to support the Open Source kraken OCR engine.

I created this draft pull request to allow public review and comments although the implementation is still incomplete. OCR for cropped image still needs testing, and there is also currently no unit test code for the new engine.

2023-08-28 07:56 UTC, samwilson commented
Also, would you mind opening a Phabricator task for this work, so it can be tracked there? Thanks!

2023-08-28 08:35 UTC, stweil commented
> Also, would you mind opening a Phabricator task for this work, so it can be tracked there? Thanks!

Done, see https://phabricator.wikimedia.org/T345055. I also updated the PR here to solve a merge conflict.

2023-08-28 08:57 UTC, stweil commented
See also my [test installation](https://ocr.1.ladenburg.world/).

2023-09-22 16:18 UTC, stweil commented
The test installation is meanwhile available on https://kraken-ocr.wmcloud.org/.

2023-12-07 09:57 UTC, Parthiv-M requested changes
This review focuses on the following main things
- Files related to Transkribus have also been modified, which I think is not ideal
- A new Transkribus model has also been added, which should be removed
- Normalise text has been added here for all engines (we would want that in a separate PR)
- Renaming the newly added API route

Overall, we'd like to keep the non-Kraken changes out of the way before testing kraken once again

2023-12-07 09:57 UTC, Parthiv-M commented on src/Controller/OcrController.php
> +	 * @Route("/api/available_segmentation_models", name="apiSegmentationModels", methods={"GET"})
This route, since it is related to Kraken, should be named `/api/kraken/available_segmentation_models`

2023-12-07 09:57 UTC, Parthiv-M commented on public/langs.json
> +    },
This Transkribus model should not be added along with Kraken changes, it would be better to separate it out

2023-12-07 09:57 UTC, Parthiv-M commented on src/Engine/TranskribusEngine.php
>  			$x = $crop['x'];
We'd prefer to isolate changes other than those related to Kraken to another PR!

2023-12-07 09:57 UTC, Parthiv-M commented on tests/Engine/EngineBaseTest.php
> +		$this->krakenEngine = $this->instantiateEngine( 'kraken' );
`instantiate()` fixed in #115

2023-12-07 09:57 UTC, Parthiv-M commented on config/packages/nelmio_api_doc.yaml
> +            version: 1.4.0
I believe it has been bumped up to 1.4.4 now.

2023-12-07 09:57 UTC, Parthiv-M commented on config/packages/nelmio_api_doc.yaml
> +            - ^/api/available_segmentation_models$
Will need to change this in accordance with my comment on route path

2023-12-07 09:57 UTC, Parthiv-M commented on i18n/en.json
> +    "title": "WikimediaOCR – Kraken Test",
This should remain as **WikimediaOCR**

2023-12-07 09:57 UTC, Parthiv-M commented on package.json
> +        "stylelint": "^15.10.3",
`stylelint` can be removed from this PR as well

2023-12-07 09:57 UTC, Parthiv-M commented on package.json
> +    "dependencies": {}
Empty entries should be removed

2023-12-07 09:57 UTC, Parthiv-M commented on src/Engine/EngineBase.php
> +		'german-fraktur-19th-20th-century' => 'German Fraktur 19th-20th century',
This is a Transkribus model and needs to be removed from this PR

2023-12-12 21:03 UTC, stweil commented on src/Controller/OcrController.php
> +	 * @Route("/api/available_segmentation_models", name="apiSegmentationModels", methods={"GET"})
Having segmentation models is not kraken specific. All OCR processes require a segmentation step, and if that step uses AI, it also requires a model. That's why I did not use a route with "kraken" here. So even if it is currently only used for kraken, I'd suggest to use a generic route.

2025-05-02 06:55 UTC, wrznr commented
It is actually a pitty that this PR never got merged. It would have been a great tool for the transcription of texts on wikisource.

2025-05-02 07:16 UTC, stweil commented
So let me fix the conflicts first.

2026-05-02 16:09 UTC, samwilson commented
I've moved this PR to https://gitlab.wikimedia.org/toolforge-repos/ocr/-/merge_requests/2

2026-05-02 16:09 UTC, closed without merging

2026-05-02 16:35 UTC, stweil commented
@samwilson, do I need a new account for gitlab.wikimedia.org? Or is one of my existing accounts also valid there?

2026-05-02 16:42 UTC, samwilson commented
You should be able to log in there with your Wikimedia developer account. Let me know if you have any issues though.

I can bring the patch up to date. I feel bad that I dropped the ball on this last year. I'm also thinking that we need to do some Apache proxy config so that kraken requests get forwarded to the right server.

2026-05-02 17:00 UTC, stweil commented
I get this message on gitlab.wikimedia.org: "Your account is pending approval from your GitLab administrator and hence blocked. Please contact your GitLab administrator if you think this is an error."

2026-05-02 17:56 UTC, samwilson commented
I've added you to trusted-contributors: https://phabricator.wikimedia.org/feed/7635354101851466613/

I think you might need to log in to Phabricator with your developer account, at the moment you don't have a ldap username linked: https://phabricator.wikimedia.org/p/sweil/